name: Trees Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - Trees/**
      - .github/workflows/trees-test.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - Trees/**
      - .github/workflows/trees-test.yml

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Trees
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test Trees
      run: go test --timeout 30m --count 100
